FROM containership/android-base:latest

# temporary hack for adb timeout
WORKDIR /home/ubuntu/buck
RUN sed -i 's/ADB_CONNECT_TIMEOUT_MS\ =\ 5000/ADB_CONNECT_TIMEOUT_MS\ =\ 60000/' src/com/facebook/buck/android/AdbHelper.java
RUN sed -i 's/ADB_CONNECT_TIMEOUT_MS\ =\ 5000/ADB_CONNECT_TIMEOUT_MS\ =\ 60000/' src/com/facebook/buck/testrunner/InstrumentationTestRunner.java
RUN ant
WORKDIR /app

# run buck fetches since we modified codebase
RUN buck fetch ReactAndroid/src/test/java/com/facebook/react/modules
RUN buck fetch ReactAndroid/src/main/java/com/facebook/react
RUN buck fetch ReactAndroid/src/main/java/com/facebook/react/shell
RUN buck fetch ReactAndroid/src/test/...
RUN buck fetch ReactAndroid/src/androidTest/...

CMD bash test.sh
